# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo "Starting deployment pipeline..."
    - step:
        name: Deploy to test
        deployment: staging   # can be test, staging or production.
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying to staging..."
          - ssh -tt root@138.197.130.167 << EOF
          - cd unravel-api-gateway
          - git pull
          - npm install
          - echo "Deploy to staging successful."
          - echo "Launching staging server..."
          - pm2 restart index.js
          - exit $?
          - EOF
          - echo "Staging server started successfully."
          - echo "Staging environment deployed successfully!"

